package pl.commercelink.web.catalog;

import org.springframework.web.util.UriUtils;

import java.nio.charset.StandardCharsets;

/** Addresses of the product catalog pages. Ids are generated by the application and safe in a path; marketplace names come from adapters and are encoded. */
public final class CatalogPaths {

    public static final String ROOT = "/dashboard/catalogs";

    private CatalogPaths() {
    }

    public static String catalogs() {
        return ROOT;
    }

    public static String newCatalog() {
        return ROOT + "/new";
    }

    public static String catalog(String catalogId) {
        return ROOT + "/" + catalogId;
    }

    public static String catalogSettings(String catalogId) {
        return catalog(catalogId) + "/settings";
    }

    public static String catalogDelete(String catalogId) {
        return catalog(catalogId) + "/delete";
    }

    public static String newCategory(String catalogId) {
        return catalog(catalogId) + "/category/new";
    }

    public static String category(String catalogId, String categoryId) {
        return catalog(catalogId) + "/category/" + categoryId;
    }

    public static String categorySettings(String catalogId, String categoryId) {
        return category(catalogId, categoryId) + "/settings";
    }

    public static String categoryBasics(String catalogId, String categoryId) {
        return categorySettings(catalogId, categoryId) + "/basics";
    }

    public static String categoryPricing(String catalogId, String categoryId) {
        return categorySettings(catalogId, categoryId) + "/pricing";
    }

    public static String categoryMarketplaces(String catalogId, String categoryId) {
        return categorySettings(catalogId, categoryId) + "/marketplaces";
    }

    public static String categoryMarketplace(String catalogId, String categoryId, String marketplace) {
        return categoryMarketplaces(catalogId, categoryId) + "/" + UriUtils.encodePathSegment(marketplace, StandardCharsets.UTF_8);
    }

    public static String categoryMarketplaceDelete(String catalogId, String categoryId, String marketplace) {
        return categoryMarketplace(catalogId, categoryId, marketplace) + "/delete";
    }

    public static String categoryFilters(String catalogId, String categoryId) {
        return categorySettings(catalogId, categoryId) + "/filters";
    }

    public static String categoryDelete(String catalogId, String categoryId) {
        return category(catalogId, categoryId) + "/delete";
    }

    public static String productsAdd(String catalogId, String categoryId) {
        return category(catalogId, categoryId) + "/products/add";
    }

    public static String productsAddReview(String catalogId, String categoryId) {
        return productsAdd(catalogId, categoryId) + "/review";
    }

    public static String productsAddSave(String catalogId, String categoryId) {
        return productsAdd(catalogId, categoryId) + "/save";
    }

    public static String newProduct(String catalogId, String categoryId) {
        return category(catalogId, categoryId) + "/products/new";
    }

    public static String product(String catalogId, String categoryId, String productId) {
        return category(catalogId, categoryId) + "/products/" + productId;
    }

    public static String productDelete(String catalogId, String categoryId, String productId) {
        return product(catalogId, categoryId, productId) + "/delete";
    }

    public static String productsBulk(String catalogId, String categoryId) {
        return category(catalogId, categoryId) + "/products/bulk";
    }
}
