spring.config.import=optional:file:./.ministack-data/.cognito.env[.properties]

spring.security.oauth2.client.registration.cognito.client-id=${COGNITO_CLIENT_ID}
spring.security.oauth2.client.registration.cognito.client-secret=${COGNITO_CLIENT_SECRET}
spring.security.oauth2.client.registration.cognito.redirect-uri=http://localhost:8080/login/oauth2/code/cognito
spring.security.oauth2.client.provider.cognito.issuer-uri=http://localhost:4566/${COGNITO_USER_POOL_ID}

cognito.domain=http://localhost:4566
cognito.logout.redirect-uri=http://localhost:8080/logout-success
