application.locale=pl
application.home=/dashboard

app.domain=http://localhost:8080
api.domain=http://localhost:8080
app.cors=http://localhost:8080

s3.bucket.feeds=feeds
s3.bucket.pricelists=pricelists
s3.bucket.stores=stores
s3.bucket.datalake=datalake

amazon.aws.region=eu-central-1

spring.application.name=Commerce Link
spring.main.allow-bean-definition-overriding=true

server.servlet.session.timeout=8h

spring.security.oauth2.client.registration.cognito.client-id=
spring.security.oauth2.client.registration.cognito.client-secret=
spring.security.oauth2.client.registration.cognito.redirect-uri=http://localhost:8080/login/oauth2/code/cognito
spring.security.oauth2.client.provider.cognito.issuer-uri=

cognito.domain=
cognito.logout.redirect-uri=http://localhost:8080/logout-success

sentry.enabled=false
sentry.dsn=
sentry.send-default-pii=false
sentry.traces-sample-rate=1.0
sentry.environment=local
sentry.release=commercelink@1.0.0

spring.cache.type=caffeine
spring.cache.cache-names=pricelists
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=10m,recordStats

spring.cloud.aws.sqs.listener.max-concurrent-messages=3
spring.cloud.aws.sqs.listener.max-messages-per-poll=3
spring.cloud.aws.sqs.listener.poll-timeout=20s

logging.level.root=INFO
logging.level.org.apache.http.wire=INFO

sqs.pricelist.queue.arn=
eventbridge.scheduler.role.arn=
