package pl.commercelink.stores;

public enum StoreNotificationType {
    UNAUTHENTICATED,
    WELCOME,
    MARKETPLACE_RETURN_REFUNDED,
    MARKETPLACE_RETURN_UNMATCHED,
    RECEIPT_ATTENTION,
    DELIVERY_REQUEST_REJECTED,
    WAREHOUSE_SHIPMENT_CREATED,
    WAREHOUSE_SHIPMENT_FAILED,
    WAREHOUSE_SHIPMENT_PICKUP,
    RMA_RETURN_SHIPMENT_FAILED,
    RMA_RETURN_PICKUP_FAILED
}
