package pl.commercelink.marketplace;

public enum MarketplaceExportSkipReason {
    CATEGORY_NOT_CONFIGURED_FOR_MARKETPLACE,
    CATEGORY_MARKETPLACE_DEFINITION_DISABLED,
    PRODUCT_DISABLED,
    PRODUCT_WITHOUT_PIM_ID,
    PRODUCT_NOT_IN_PRICELIST,
    PRODUCT_NOT_APPROVED_FOR_MARKETPLACE,
    QUANTITY_ZEROED_BELOW_WAREHOUSE_THRESHOLD,
    QUANTITY_ZEROED_BELOW_DISTRIBUTOR_THRESHOLDS;

    public boolean isQuantityZeroed() {
        return this == QUANTITY_ZEROED_BELOW_WAREHOUSE_THRESHOLD
                || this == QUANTITY_ZEROED_BELOW_DISTRIBUTOR_THRESHOLDS;
    }
}
